spring.application.name=iam-server

server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/iam_db

spring.datasource.username=postgres

spring.datasource.password=RAMGARU

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration (Week 3: Caching, Tokens & Sessions)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# MFA Configuration (Week 3: Twilio SMS / SendGrid Email)
mfa.sendgrid.api-key=
mfa.twilio.account-sid=
mfa.twilio.auth-token=
mfa.twilio.from-number=